Try finding best available Python

diff --git a/cbi b/cbi
--- a/cbi
+++ b/cbi
@@ -1,4 +1,15 @@
-#!/usr/bin/env python3
+#!/usr/bin/env sh
+''':'
+# Find the "best" installed Python:
+for ver in 3.14 3.13 3.12 3.11 3.10 3.9 3; do
+  if command -v "python$ver" >/dev/null 2>&1; then
+    exec "python$ver" "$0" "$@"
+  fi
+done
+echo "Error: No suitable Python found." >&2
+exit 1
+':'''
+
 import os
 import sys
 import shutil
@@ -10,6 +21,11 @@ from pprint import pprint, pformat
 
 from argparse import ArgumentParser
 from pathlib import Path
+
+if sys.version_info < (3, 9):
+    sys.exit("Need Python ≥ 3.9")
+
+
 
 progname = os.path.basename(sys.argv[0])
 version  = "0.42.1"
